version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: fastnote-react
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "test"]
