name: Frontend CI/CD

on:
  push:
    branches:
      - release
    # paths:
    #   - 'frontend/**'
  pull_request:
    branches:
      - release
    # paths:
    #   - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build
      env:
        REACT_APP_GOOGLE_CLIENT: ${{ secrets.REACT_APP_GOOGLE_CLIENT }}
        REACT_APP_S3_BASE_URL: ${{ secrets.REACT_APP_S3_BASE_URL }}
        REACT_APP_HOST: ${{ secrets.REACT_APP_HOST }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_BUCKET_REGION }}

    - name: Copy build to S3
      run: aws s3 cp build s3://fastnote-space/ --recursive --acl bucket-owner-full-control

    - name: Clear CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id E8C9HX9SUROOZ --paths "/*"
